name: Semantic Release

on:
  push:
    branches:
      - master
      - develop
      - hotfix/*
      - release/*

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cycjimmy/semantic-release-action@v4
        id: release
        with:
          semantic_version: 24
          ci: true
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            conventional-changelog-conventionalcommits
            @semantic-release/changelog
            @semantic-release/github
            @semantic-release/git
            @saithodev/semantic-release-backmerge
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: noreply@mercedes-benz.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: noreply@mercedes-benz.com